### ISSUE TITLE
TypeError: Cannot read property 'sessionAttributes' of undefined

### ISSUE THREAD

**Issue by ghachey** [kompot/nhl-tv-geeky-streams#43]
Getting this error.

```
$ yarn start
yarn run v1.21.1
$ ./node_modules/.bin/ts-node src/index.ts
? Choose game to download ⤺  one day back
? Choose game to download   Pittsburgh Penguins     @ Philadelphia Flyers    
? Choose feed to watch NATIONAL, NBCSN
(node:46190) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sessionAttributes' of undefined
    at /Users/user/opt/nhl-tv-geeky-streams/src/index.ts:146:46
    at step (/Users/user/opt/nhl-tv-geeky-streams/src/index.ts:33:23)
    at Object.next (/Users/user/opt/nhl-tv-geeky-streams/src/index.ts:14:53)
    at fulfilled (/Users/user/opt/nhl-tv-geeky-streams/src/index.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:46190) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46190) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 14.93s.
```

**Comment by rubenflamshepherd** [comment]
+1 to this. I am also getting this error on Mac

**Comment by kompot** [comment]
yep, I guess that's because of bad nhl.tv credentials, should make it more explicit

**Comment by zbisch** [comment]
Just wanted to chime in with a similar issue. I've been using this tool to download some games (mostly) without issues. However, this error consistently appears for me for one game in particular ([https://www.nhl.com/gamecenter/2015020643](Bos vs Phi)), so it doesn't seem to be a credentials issue. I tried a few other random games around mid- to late- Jan in 2016 and this error seems to appear for most games in that date range. Streaming that game in my browser works fine, but does seem to be limited to a lower quality.

**Comment by rseanhall** [comment]
This became obsolete when they retired the old NHL.TV last season.
