### ISSUE TITLE
Failed to parse session information

### ISSUE THREAD

**Issue by ghachey** [kompot/nhl-tv-geeky-streams#44]
$ nhltv --team PIT -u myuser@outlook.com -p mypassword
Jan 23 08:15:23 - Logging in to NHL.com..
Jan 23 08:15:24 - Looking up games..
Traceback (most recent call last):
  File "/Users/myuser/.venvs/nhl/bin/nhltv", line 11, in <module>
    load_entry_point('nhltv==2.1.2', 'console_scripts', 'nhltv')()
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/nhltv_lib/main.py", line 39, in main
    run_loop()
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/nhltv_lib/main.py", line 44, in run_loop
    loop()
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/nhltv_lib/main.py", line 48, in loop
    get_and_download_games()
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/nhltv_lib/main.py", line 71, in get_and_download_games
    download(i)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/nhltv_lib/main.py", line 79, in download
    dl: Download = download_game(stream)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/nhltv_lib/download.py", line 41, in download_game
    download = _get_download_from_stream(stream)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/nhltv_lib/download.py", line 105, in _get_download_from_stream
    media_auth: str = _extract_media_auth(stream_json)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/nhltv_lib/download.py", line 190, in _extract_media_auth
    f"Failed to parse session information\n"
nhltv_lib.exceptions.RequestFailed: Failed to parse session information
error code: 1
status: Success Status

This is in a clean venv with python 3.7.1 on Mac OS X 10.14

**Comment by ghachey** [comment]
Wrong github repio, sorry.
