### ISSUE TITLE
UTAH Hockey Club error

### ISSUE THREAD

**Issue by Redmax87** [kompot/nhl-tv-geeky-streams#80]
I have an error for today games
yarn run v1.22.19
$ ./node_modules/.bin/ts-node src/index.ts
/app/src/nhltvProvider.ts:151
    throw new Error(JSON.stringify(team));
          ^
Error: {"id":59,"name":{"default":"Utah Hockey Club","fr":"Club de hockey de l'Utah"},"abbrev":"UTA","record":" - - ","logo":"https://assets.nhle.com/logos/nhl/svg/UTA_light.svg"}
    at getProviderTeam (/app/src/nhltvProvider.ts:151:11)
    at new NhltvGame (/app/src/nhltvProvider.ts:43:21)
    at processGame (/app/src/nhltvProvider.ts:159:21)
    at /app/src/nhltvProvider.ts:180:12
    at Array.map (<anonymous>)
    at getNhltvGameList (/app/src/nhltvProvider.ts:179:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getGameList (/app/src/index.ts:179:22)
    at async main (/app/src/index.ts:84:22)
error Command failed with exit code 1.

**Comment by un999** [comment]
Also getting an error with Utah

yarn run v1.22.19
$ ./node_modules/.bin/ts-node src/index.ts
(node:28332) UnhandledPromiseRejectionWarning: Error: {"id":59,"name":{"default":"Utah Hockey Club","fr":"Club de hockey de l'Utah"},"abbrev":"UTA","record":" - - ","logo":"https://assets.nhle.com/logos/nhl/svg/UTA_light.svg"}
    at getProviderTeam (/src/nhltvProvider.ts:151:11)
    at new NhltvGame (/src/nhltvProvider.ts:42:21)
    at processGame (/src/nhltvProvider.ts:159:21)
    at /src/nhltvProvider.ts:180:12
    at Array.map (<anonymous>)
    at getNhltvGameList (/src/nhltvProvider.ts:179:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getGameList (/src/index.ts:179:22)
    at async main (/src/index.ts:84:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rseanhall** [comment]
Thanks for the bug reports, fixed in https://github.com/kompot/nhl-tv-geeky-streams/commit/12bd0d5327cdb76d38e14b2352f0edc3b701bba3
